// Code generated by mockery v2.20.0. DO NOT EDIT.

package repomock

import (
	context "context"

	entity "github.com/Kin-dza-dzaa/task/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CurrencyRepo is an autogenerated mock type for the CurrencyRepo type
type CurrencyRepo struct {
	mock.Mock
}

// CreateRates provides a mock function with given fields: ctx, rates
func (_m *CurrencyRepo) CreateRates(ctx context.Context, rates []entity.Rate) error {
	ret := _m.Called(ctx, rates)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.Rate) error); ok {
		r0 = rf(ctx, rates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rates provides a mock function with given fields: ctx, date, code
func (_m *CurrencyRepo) Rates(ctx context.Context, date time.Time, code string) ([]entity.Rate, error) {
	ret := _m.Called(ctx, date, code)

	var r0 []entity.Rate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string) ([]entity.Rate, error)); ok {
		return rf(ctx, date, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string) []entity.Rate); ok {
		r0 = rf(ctx, date, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Rate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, string) error); ok {
		r1 = rf(ctx, date, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCurrencyRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyRepo creates a new instance of CurrencyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyRepo(t mockConstructorTestingTNewCurrencyRepo) *CurrencyRepo {
	mock := &CurrencyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
