// Code generated by mockery v2.20.0. DO NOT EDIT.

package repomock

import (
	context "context"

	entity "github.com/Kin-dza-dzaa/task/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CurrencyAPI is an autogenerated mock type for the CurrencyAPI type
type CurrencyAPI struct {
	mock.Mock
}

// Rates provides a mock function with given fields: ctx, date
func (_m *CurrencyAPI) Rates(ctx context.Context, date time.Time) ([]entity.Rate, error) {
	ret := _m.Called(ctx, date)

	var r0 []entity.Rate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]entity.Rate, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []entity.Rate); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Rate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCurrencyAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewCurrencyAPI creates a new instance of CurrencyAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCurrencyAPI(t mockConstructorTestingTNewCurrencyAPI) *CurrencyAPI {
	mock := &CurrencyAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
