basePath: /v1
definitions:
  github_com_Kin-dza-dzaa_task_internal_entity.Rate:
    properties:
      change:
        type: string
      code:
        type: string
      quant:
        type: integer
      rate:
        type: number
      title:
        type: string
      valid_at:
        type: string
    type: object
  internal_transport_http_v1_rest.GetRatesResponse:
    properties:
      rates:
        items:
          $ref: '#/definitions/github_com_Kin-dza-dzaa_task_internal_entity.Rate'
        type: array
    type: object
  internal_transport_http_v1_rest.httpResponse:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
  description: REST API for currency rates to KZT.
  title: Rate API
  version: "0.1"
paths:
  /rates/{date}:
    get:
      parameters:
      - description: 'Date in format: 11.11.2011'
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Rates
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.GetRatesResponse'
        "400":
          description: Invalid date
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
      summary: Gets all rates by given date.
      tags:
      - rates
    post:
      parameters:
      - description: 'Date in format: 11.11.2011'
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Request is accepted and is being proccessed
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
        "400":
          description: Invalid date
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
      summary: Makes call to external API and populates DB asynchronously.
      tags:
      - rates
  /rates/{date}/{code}:
    get:
      parameters:
      - description: 'Date in format: 11.11.2011'
        in: path
        name: date
        required: true
        type: string
      - description: 'Code of currency: KZT'
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Rates
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.GetRatesResponse'
        "400":
          description: Invalid date
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/internal_transport_http_v1_rest.httpResponse'
      summary: Gets all rates by given date and code.
      tags:
      - rates
swagger: "2.0"
